image: go1.2
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
script:
- createdb -h localhost -U postgres drone
- psql -U postgres -h localhost -c "CREATE TABLE \"mock_table\" (s text, i int)" drone
- cd postgres
- go get ./...
- go get github.com/stretchr/testify/assert
- go test
services:
- postgres
