image: go1.2
services:
- postgres
notify:
  email:
    recipients:
    - drone@clever.com
  hipchat:
    on_failure: true
    on_started: true
    on_success: true
    room: Clever-Dev-CI
    token: {{hipchatToken}}
script:
- ./test_drone.sh
